name: KERKOM
favicon: null
layout_spectrum: 0.7506194866728038
typography_spectrum: 0.9554738400038332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.32246095198206604
  lightness: 0.37206747103482485
  saturation: 0.6519035170786083
  rhythmicContrast: 0.29519604588858783
purpose: []
